home-directory: "/Users/scottgregory/Documents/gits/mlflow_afl"
flaml:
    settings:
        time_budget: 4000
        # metric: "log_loss"
        task: "classification"
        log_file_name: "experiment.log"
        seed: 7654321
        verbose: 0
        ensemble: true
        estimator_list:
            # - "lgbm"
            - "xgboost"
            # - "rf"
            # - "lgbm"
        eval_method: "cv"
        n_splits: 5

data:
    training:
        test_year: 2022
        train_cols:
            # - "rolling_for"
            # - "rolling_for_joined"
            # - "rolling_against"
            # - "rolling_against_joined"
            - "rolling_margin"
            - "rolling_margin_joined"
            # - "rolling_percentage"
            # - "rolling_percentage_joined"
            # - "rolling_wins"
            # - "rolling_wins_joined"
            # - "game_points"
            # - "game_points_joined"
            - "rolling_game_points"
            - "rolling_game_points_joined"
            # - "percentage_wins"
            # - "percentage_wins_joined"
            - "rolling_wins_1"
            - "rolling_wins_1_joined"
            - "rolling_wins_2"
            - "rolling_wins_2_joined"
            - "rolling_wins_3"
            - "rolling_wins_3_joined"
            # - "rolling_F_median_1"
            # - "rolling_F_median_1_joined"
            # - "rolling_A_median_1"
            # - "rolling_A_median_1_joined"
            # - "rolling_M_median_1"
            # - "rolling_M_median_1_joined"
            # - "rolling_F_sum_1"
            # - "rolling_F_sum_1_joined"
            # - "rolling_A_sum_1"
            # - "rolling_A_sum_1_joined"
            # - "rolling_M_sum_1"
            # - "rolling_M_sum_1_joined"
            - "rolling_M_1"
            - "rolling_M_1_joined"
            - "rolling_M_2"
            - "rolling_M_2_joined"
            - "rolling_M_3"
            - "rolling_M_3_joined"
            # - "rolling_M_median_2"
            # - "rolling_M_median_2_joined"
            # - "rolling_M_median_3"
            # - "rolling_M_median_3_joined"
            - "prev_match_M_1"
            - "prev_match_M_1_joined"
            - "prev_match_M_2"
            - "prev_match_M_2_joined"
            - "prev_match_M_3"
            - "prev_match_M_3_joined"
            - "prev_match_M_4"
            - "prev_match_M_4_joined"
            # - "prev_match_M_5"
            # - "prev_match_M_5_joined"
            # - "prev_match_M_6"
            # - "prev_match_M_6_joined"
            # - "prev_match_M_7"
            # - "prev_match_M_7_joined"
            # - "prev_match_M_8"
            # - "prev_match_M_8_joined"
            # - "prev_match_M_9"
            # - "prev_match_M_9_joined"
            # - "prev_match_M_10"
            # - "prev_match_M_10_joined"
            # - "prev_match_M_11"
            # - "prev_match_M_11_joined"
            - "round_num"
            # - "rolling_percentage_1"
            # - "rolling_percentage_1_joined"
            # - "home_rolling_for"
            # - "home_rolling_for_joined"
            # - "home_rolling_against"
            # - "home_rolling_against_joined"
            - "early"
            - "mid"
        target: "win"
    feature_set: "/data/processed/processed_features.csv"
